import Head from 'next/head'
import { GetStaticProps } from 'next'
import { getAllImages, getGalleryContent } from 'lib/api'
import MediaNav from 'src/components/MediaNav'
import EmblaCarousel from 'src/components/EmblaCarousel'
import ReactHtmlParser, { processNodes, convertNodeToElement, htmlparser2 } from 'react-html-parser';

export default function Index({ allImages: { nodes }, galleryContent: { nodes: galleryNodes } }) {
    const sources = [];
    ReactHtmlParser(galleryNodes[0]?.content, {
        transform: ({ type, name, attribs }) => {
            const { src, title } = attribs
            // Parsing out dupe images generated by wordpress
            if (type === 'tag' && name === 'img' && title) {
                sources.push({
                    sourceUrl: src, title, alt: title
                })
            }
        }
    })

    return (
        <>
            <Head>
                <title>Duncan Moore | Gallery</title>
            </Head>
            <MediaNav />
            <section className="sandbox__carousel">
                <EmblaCarousel slides={sources} options={{}} />
            </section>

        </>
    )
}

export const getStaticProps: GetStaticProps = async ({ preview = false }) => {
    const allImages = await getAllImages()
    const galleryContent = await getGalleryContent();
    return {
        props: { allImages, galleryContent, preview },
        revalidate: 10,
    }
}
